#!/usr/bin/bash
USER=$1
PASSWD=$2
ssh_port=$3
nx_port=$4
useradd -m $USER
echo "$USER:$PASSWD" | chpasswd
echo "$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
echo "1.添加用户$USER成功"
apt install xfce4 xfce4-goodies papirus-icon-theme
echo "2.安装xfce4桌面成功"
wget https://download.nomachine.com/download/7.7/Linux/nomachine_7.7.4_1_amd64.deb -q
apt install ./nomachine_7.7.4_1_amd64.deb
echo "3.安装nomachine成功"
sed -i 's|"/etc/X11/Xsession default"|"exec startxfce4"|g' /usr/NX/etc/node.cfg
echo "4.修改node.cfg成功"
cd /home/$USER/
wget https://git.io/theme.tar.xz -q
tar xvf theme.tar.xz
mv theme-and-background/ZorinBlue-Dark /usr/share/themes/
echo "5.安装ZorinBlue-Dark成功"
#systemctl restart nxserver
#/usr/NX/bin/nxserver --restart
#echo "6.重启nxserver成功"
wget https://git.io/ayafrp.tar.xz -q
tar xvf ayafrp.tar.xz
echo "[ssh-$(date '+%Y%m%d-%H.%M.%S')]" >> ./frpc.ini
echo "type = tcp" >> ./frpc.ini
echo "local_port = 22" >> ./frpc.ini
echo "remote_port = $ssh_port" >> ./frpc.ini
echo "[nx-$(date '+%Y%m%d-%H.%M.%S')]" >> ./frpc.ini
echo "type = tcp" >> ./frpc.ini
echo "local_port = 4000" >> ./frpc.ini
echo "remote_port = $nx_port" >> ./frpc.ini
nohup ./frpc -c frpc.ini&
echo "6.启动frpc成功!"
MSG="ssh $USER@[ip] -p $ssh_port\\nNxplayer: [ip]:$nx_port"
curl 'http://t.aya1.top:5700/send_msg?access_token=ayatale&message_type=group&group_id=204097403&message=$MSG'
for i in {1..2100};do
    sleep 10
    echo "$[10*i]s...\nssh $USER@g.aya1.top -p $ssh_port\nNxplayer: g.aya1.top:$nx_port"
done